# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will download a prebuilt Ruby version, install dependencies and run tests with Rake
# For more information see: https://github.com/marketplace/actions/setup-ruby-jruby-and-truffleruby

name: Run Cucumber Tests

on:
  [push]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby
      with:
        ruby-version: 2.7

    - name: Install dependencies
      run: bundle install

    - name: Start server
      run: bundle exec rackup -p 3000 &

    - name: Run tests
      run: bundle exec cucumber

